import os
from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = os.environ["ELASTIC_PASSWORD"]

# Create the client instance
client = Elasticsearch(
    "https://localhost:9200",
    ca_certs="./other_http_ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
print(client.info())
